"""add metrics jsonb

Revision ID: 1980f20e2c59
Revises: d1c93ec68207
Create Date: 2026-02-14 13:51:36.784616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1980f20e2c59'
down_revision: Union[str, Sequence[str], None] = 'd1c93ec68207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_analyses_dataset_id'), 'analyses', ['dataset_id'], unique=False)
    op.drop_constraint(op.f('analyses_dataset_id_fkey'), 'analyses', type_='foreignkey')
    op.create_foreign_key(None, 'analyses', 'datasets', ['dataset_id'], ['id'], ondelete='CASCADE')
    op.drop_column('analyses', 'outlier_count')
    op.drop_column('analyses', 'mean_value')
    op.drop_column('analyses', 'min_value')
    op.drop_column('analyses', 'std_dev')
    op.drop_column('analyses', 'max_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('max_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('analyses', sa.Column('std_dev', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('analyses', sa.Column('min_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('analyses', sa.Column('mean_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('analyses', sa.Column('outlier_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.create_foreign_key(op.f('analyses_dataset_id_fkey'), 'analyses', 'datasets', ['dataset_id'], ['id'])
    op.drop_index(op.f('ix_analyses_dataset_id'), table_name='analyses')
    op.alter_column('analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('analyses', 'metrics')
    # ### end Alembic commands ###
