"""add analysis fields

Revision ID: 5d3f0cf73d54
Revises: 1980f20e2c59
Create Date: 2026-02-14 21:04:02.743256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d3f0cf73d54'
down_revision: Union[str, Sequence[str], None] = '1980f20e2c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('summary', sa.JSON(), nullable=False))
    op.add_column('analyses', sa.Column('outliers', sa.JSON(), nullable=False))
    op.add_column('analyses', sa.Column('insights', sa.JSON(), nullable=False))
    op.add_column('analyses', sa.Column('dataset_health', sa.String(), nullable=False))
    op.add_column('analyses', sa.Column('risk_level', sa.String(), nullable=False))
    op.alter_column('analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_analyses_dataset_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_column('analyses', 'metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_index(op.f('ix_analyses_dataset_id'), 'analyses', ['dataset_id'], unique=False)
    op.alter_column('analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('analyses', 'risk_level')
    op.drop_column('analyses', 'dataset_health')
    op.drop_column('analyses', 'insights')
    op.drop_column('analyses', 'outliers')
    op.drop_column('analyses', 'summary')
    # ### end Alembic commands ###
